# This is a Rust Manifest as defined at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [ "blinky", "button", "eeprom", "fade","hello_beagle"]

[workspace.package]
license = "MIT"
authors = ["Ayush Singh <ayush@beagleboard.org>"]
edition = "2021"
