#[cfg(feature = "button")]
pub mod button;
#[cfg(feature = "led")]
pub mod led;
#[cfg(feature = "pwm_led")]
pub mod pwm_led;
#[cfg(feature = "beagle_eeprom")]
pub mod beagle_eeprom;
#[cfg(feature = "light_sensor")]
pub mod light_sensor;
#[cfg(feature = "seven_segment")]
pub mod seven_segment;

#[cfg(feature = "button")]
pub use button::Button;
#[cfg(feature = "led")]
pub use led::Led;
#[cfg(feature = "pwm_led")]
pub use pwm_led::PwmLed;
#[cfg(feature = "beagle_eeprom")]
pub use beagle_eeprom::*;
#[cfg(feature = "light_sensor")]
pub use light_sensor::LightSensor;
#[cfg(feature = "seven_segment")]
pub use seven_segment::SevenSegment;
